In [44]:
######################################
######################################
######################################
######################################
#CREATING NEW DEMAND DATASET WITH ALL ZEROS INCLUDED
#######################################
######################################
#######################################
######################################
import pandas as pd
demand_2017= pd.read_csv('demand_data_2017.csv')

C:\Users\blein\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:2717: DtypeWarning: Columns (3,4,5,6,7) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [27]:
demand_2017.shape
demand_2017= demand_2017.iloc[1:, 1:4]
demand_2017.head()

      time_block  PULocationID passenger_count
1  2017/01/01 00           4.0             135
2  2017/01/01 00          12.0               3
3  2017/01/01 00          13.0             104
4  2017/01/01 00          24.0              94
5  2017/01/01 00          43.0             401

In [34]:
demand_2017[['time_block', 'PULocationID']]

           time_block  PULocationID
1       2017/01/01 00           4.0
2       2017/01/01 00          12.0
3       2017/01/01 00          13.0
4       2017/01/01 00          24.0
5       2017/01/01 00          43.0
6       2017/01/01 00          45.0
7       2017/01/01 00          48.0
8       2017/01/01 00          50.0
9       2017/01/01 00          68.0
10      2017/01/01 00          79.0
11      2017/01/01 00          87.0
12      2017/01/01 00          88.0
13      2017/01/01 00          90.0
14      2017/01/01 00         100.0
15      2017/01/01 00         107.0
16      2017/01/01 00         113.0
17      2017/01/01 00         114.0
18      2017/01/01 00         125.0
19      2017/01/01 00         137.0
20      2017/01/01 00         140.0
21      2017/01/01 00         141.0
22      2017/01/01 00         142.0
23      2017/01/01 00         143.0
24      2017/01/01 00         144.0
25      2017/01/01 00         148.0
26      2017/01/01 00         151.0
27      2017/01/01 00         158.0
28      2017/01/01 00         161.0
29      2017/01/01 00         162.0
30      2017/01/01 00         163.0
...               ...           ...
444721  2017/12/31 23         142.0
444722  2017/12/31 23         143.0
444723  2017/12/31 23         144.0
444724  2017/12/31 23         148.0
444725  2017/12/31 23         151.0
444726  2017/12/31 23         158.0
444727  2017/12/31 23         161.0
444728  2017/12/31 23         162.0
444729  2017/12/31 23         163.0
444730  2017/12/31 23         164.0
444731  2017/12/31 23         170.0
444732  2017/12/31 23         186.0
444733  2017/12/31 23         209.0
444734  2017/12/31 23         211.0
444735  2017/12/31 23         224.0
444736  2017/12/31 23         229.0
444737  2017/12/31 23         230.0
444738  2017/12/31 23         231.0
444739  2017/12/31 23         232.0
444740  2017/12/31 23         233.0
444741  2017/12/31 23         234.0
444742  2017/12/31 23         236.0
444743  2017/12/31 23         237.0
444744  2017/12/31 23         238.0
444745  2017/12/31 23         239.0
444746  2017/12/31 23         246.0
444747  2017/12/31 23         249.0
444748  2017/12/31 23         261.0
444749  2017/12/31 23         262.0
444750  2017/12/31 23         263.0

[444750 rows x 2 columns]

In [40]:
zerodata = demand_2017.groupby(['time_block','PULocationID']).sum().unstack(fill_value=0).stack()

AttributeError: 'Series' object has no attribute 'stack'

In [42]:
zerodata.head

<bound method NDFrame.head of                            passenger_count
time_block    PULocationID
2017/01/01 00 4.0                      135
              12.0                       3
              13.0                     104
              24.0                      94
              43.0                     401
              45.0                      54
              48.0                     697
              50.0                     315
              68.0                     664
              79.0                    1076
              87.0                     150
              88.0                      70
              90.0                     470
              100.0                    100
              107.0                    628
              113.0                    318
              114.0                    406
              125.0                     99
              137.0                    305
              140.0                    230
              141.0                    525
              142.0                    739
              143.0                    234
              144.0                    270
              148.0                    594
              151.0                    238
              158.0                    297
              161.0                    652
              162.0                    416
              163.0                    222
...                                    ...
2017/12/31 23 142.0                    387
              143.0                     84
              144.0                    130
              148.0                    197
              151.0                    123
              158.0                    161
              161.0                    249
              162.0                    273
              163.0                    127
              164.0                    205
              170.0                    211
              186.0                    212
              209.0                     25
              211.0                     86
              224.0                     23
              229.0                    202
              230.0                    119
              231.0                    151
              232.0                     32
              233.0                     92
              234.0                    273
              236.0                    286
              237.0                    247
              238.0                    299
              239.0                    290
              246.0                     90
              249.0                    238
              261.0                     48
              262.0                    103
              263.0                    256

[446760 rows x 1 columns]>

In [93]:
___, month, day_of_month, hour = zip(*zerodata['time_block'].apply(lambda x: x.replace(' ','/').split('/')))

KeyError: 'time_block'

In [43]:
zerodata.to_csv('demand_data_2017_with_zeros.csv', encoding='utf-8')

In [136]:
######################################
######################################
######################################
######################################
#CREATING NEW NEIGHBORS DATASET WITH ALL ZEROS INCLUDED
#######################################
######################################
#######################################
######################################
neighbors_2017= pd.read_csv('neighbors_data_2017_fixed.csv')

C:\Users\blein\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:2717: DtypeWarning: Columns (4,5,6,7,8,9,10) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [137]:
neighbors_2017.head

<bound method NDFrame.head of          Unnamed: 0     time_block  PULocationID  DOLocationID  \
0               NaN            NaN           NaN           NaN
1              68.0  2017/01/01 00           4.0          79.0
2              86.0  2017/01/01 00           4.0         224.0
3              88.0  2017/01/01 00           4.0         232.0
4             121.0  2017/01/01 00          13.0         231.0
5             125.0  2017/01/01 00          13.0         261.0
6             130.0  2017/01/01 00          24.0          43.0
7             137.0  2017/01/01 00          24.0         151.0
8             149.0  2017/01/01 00          43.0          24.0
9             166.0  2017/01/01 00          43.0         142.0
10            170.0  2017/01/01 00          43.0         151.0
11            175.0  2017/01/01 00          43.0         163.0
12            187.0  2017/01/01 00          43.0         236.0
13            188.0  2017/01/01 00          43.0         237.0
14            189.0  2017/01/01 00          43.0         238.0
15            190.0  2017/01/01 00          43.0         239.0
16            204.0  2017/01/01 00          45.0         144.0
17            205.0  2017/01/01 00          45.0         148.0
18            211.0  2017/01/01 00          45.0         231.0
19            212.0  2017/01/01 00          45.0         232.0
20            221.0  2017/01/01 00          48.0          50.0
21            222.0  2017/01/01 00          48.0          68.0
22            227.0  2017/01/01 00          48.0         100.0
23            236.0  2017/01/01 00          48.0         142.0
24            263.0  2017/01/01 00          48.0         246.0
25            272.0  2017/01/01 00          50.0          48.0
26            286.0  2017/01/01 00          50.0         143.0
27            307.0  2017/01/01 00          50.0         246.0
28            316.0  2017/01/01 00          68.0          48.0
29            325.0  2017/01/01 00          68.0          90.0
...             ...            ...           ...           ...
1699296  14748671.0  2017/12/31 23         237.0         141.0
1699297  14748680.0  2017/12/31 23         237.0         162.0
1699298  14748681.0  2017/12/31 23         237.0         163.0
1699299  14748690.0  2017/12/31 23         237.0         236.0
1699300  14748700.0  2017/12/31 23         238.0          43.0
1699301  14748712.0  2017/12/31 23         238.0         151.0
1699302  14748723.0  2017/12/31 23         238.0         239.0
1699303  14748731.0  2017/12/31 23         239.0          43.0
1699304  14748743.0  2017/12/31 23         239.0         142.0
1699305  14748744.0  2017/12/31 23         239.0         143.0
1699306  14748758.0  2017/12/31 23         239.0         238.0
1699307  14748765.0  2017/12/31 23         246.0          48.0
1699308  14748766.0  2017/12/31 23         246.0          50.0
1699309  14748767.0  2017/12/31 23         246.0          68.0
1699310  14748777.0  2017/12/31 23         246.0         158.0
1699311  14748798.0  2017/12/31 23         249.0          68.0
1699312  14748801.0  2017/12/31 23         249.0          90.0
1699313  14748805.0  2017/12/31 23         249.0         113.0
1699314  14748806.0  2017/12/31 23         249.0         114.0
1699315  14748807.0  2017/12/31 23         249.0         125.0
1699316  14748814.0  2017/12/31 23         249.0         158.0
1699317  14748836.0  2017/12/31 23         261.0          13.0
1699318  14748842.0  2017/12/31 23         261.0          87.0
1699319  14748843.0  2017/12/31 23         261.0          88.0
1699320  14748850.0  2017/12/31 23         261.0         231.0
1699321  14748858.0  2017/12/31 23         262.0         140.0
1699322  14748872.0  2017/12/31 23         262.0         263.0
1699323  14748889.0  2017/12/31 23         263.0         141.0
1699324  14748907.0  2017/12/31 23         263.0         236.0
1699325  14748911.0  2017/12/31 23         263.0         262.0

        passenger_count passenger_count.1       trip_distance  \
0                 count               sum                mean
1                    18                39  0.7122222222222222
2                     3                 4  0.7200000000000001
3                     4                11  1.2825000000000002
4                     8                17             1.12375
5                     3                 3                1.16
6                     1                 1                 2.5
7                     4                 4               0.455
8                     3                 3                2.18
9                    12                18  1.4225000000000003
10                    8                17  1.9637499999999997
11                    1                 1                1.33
12                   22                44  1.1968181818181816
13                   12                22  1.0583333333333333
14                   21                38  1.4404761904761902
15                   15                31   1.653333333333333
16                    2                 2                0.95
17                    3                 9  0.9766666666666667
18                    3                 5  0.8333333333333334
19                    1                 1                 1.6
20                   36                65  0.7250000000000001
21                   48                83  1.2516666666666667
22                    1                 5                1.18
23                   20                28  1.2790000000000004
24                   33                50  1.3272727272727274
25                   33                48   0.683939393939394
26                   10                16               1.065
27                   20                32              1.2235
28                   41                74  1.3753658536585365
29                   18                26  0.8894444444444445
...                 ...               ...                 ...
1699296              19                32            0.747895
1699297               6                 7            0.898333
1699298               3                 3                0.51
1699299              32                55              1.0175
1699300               7                10             1.00286
1699301              45                75            0.688222
1699302              26                44            0.820385
1699303              10                22               0.973
1699304              35                56            0.874857
1699305              14                29            0.834286
1699306              39                60            0.766154
1699307              12                16            0.758333
1699308               5                 9                0.84
1699309              10                22               0.952
1699310               1                 2                1.12
1699311              16                25            0.881875
1699312              17                29            0.777059
1699313               8                16             0.70125
1699314              12                18                0.77
1699315               5                 7               0.884
1699316              10                15               0.674
1699317               3                 4             1.00333
1699318               3                 3            0.603333
1699319               3                 4            0.486667
1699320               5                 6               1.346
1699321               6                11            0.933333
1699322               9                20            0.576667
1699323              25                37              0.7612
1699324              15                34            0.634667
1699325              17                34            0.604118

                 tip_amount tolls_amount        total_amount  \
0                       sum          sum                 sum
1                      7.51          0.0  126.40999999999997
2                       0.0          0.0                20.4
3                       3.8          0.0                36.0
4                     12.87          0.0               74.77
5                      1.66          0.0  24.560000000000002
6                       0.0          0.0                11.3
7                      1.95          0.0  23.650000000000002
8                      1.33          0.0               31.73
9        11.030000000000001          0.0              120.13
10                     5.76          0.0               87.66
11                      0.0          0.0                 8.3
12                     19.7          0.0  192.30000000000004
13                     9.11          0.0              104.71
14                    17.44          0.0  199.74000000000007
15       21.999999999999996          0.0               162.0
16                      1.0          0.0                16.6
17                      0.0          0.0  22.400000000000002
18                      1.7          0.0                22.1
19                      0.0          0.0                16.3
20                     21.8          0.0   369.6000000000002
21                    45.78          0.0   639.1799999999998
22                      0.0          0.0                17.8
23                    15.27          0.0  202.27000000000004
24                    35.19          0.0   371.0900000000002
25                    17.75          0.0  301.65000000000015
26                    16.78          0.0   93.77999999999999
27       27.070000000000004          0.0  209.57000000000005
28                    38.35          0.0   514.6500000000002
29                    15.41          0.0  161.81000000000003
...                     ...          ...                 ...
1699296               14.14            0              135.84
1699297                   2            0                42.3
1699298                   0            0                19.4
1699299               29.35            0              257.95
1699300                5.08            0               54.18
1699301               37.53            0              313.53
1699302                22.6            0               188.9
1699303                8.34            0               79.84
1699304               27.25            0              264.75
1699305                8.45            0              101.65
1699306               25.75            0              269.45
1699307                6.94            0               91.54
1699308                3.31            0               35.81
1699309               10.23            0               87.23
1699310                1.46            0                8.76
1699311               12.43            0              126.23
1699312               16.81            0              127.91
1699313               12.18            0               63.58
1699314                8.03            0               94.63
1699315                3.19            0               36.19
1699316                5.61            0               70.61
1699317                3.25            0               24.15
1699318                   0            0                19.4
1699319                1.16            0               17.56
1699320                4.56            0               42.56
1699321                 6.7            0                  48
1699322               12.12            0               83.07
1699323               23.42            0              177.92
1699324               11.02            0               99.02
1699325                  16            0               115.1

                 time_delta  month  hour  day_of_month  day_of_week    PU_DO
0                      mean    NaN   NaN           NaN          NaN      NaN
1                     303.5    1.0   0.0           1.0          6.0     4_79
2                     327.0    1.0   0.0           1.0          6.0    4_224
3                     403.5    1.0   0.0           1.0          6.0    4_232
4                   377.375    1.0   0.0           1.0          6.0   13_231
5                     396.0    1.0   0.0           1.0          6.0   13_261
6                     625.0    1.0   0.0           1.0          6.0    24_43
7                    174.75    1.0   0.0           1.0          6.0   24_151
8         477.6666666666667    1.0   0.0           1.0          6.0    43_24
9                     490.0    1.0   0.0           1.0          6.0   43_142
10                   528.25    1.0   0.0           1.0          6.0   43_151
11                    407.0    1.0   0.0           1.0          6.0   43_163
12       370.04545454545456    1.0   0.0           1.0          6.0   43_236
13                   423.75    1.0   0.0           1.0          6.0   43_237
14                    431.0    1.0   0.0           1.0          6.0   43_238
15       493.06666666666666    1.0   0.0           1.0          6.0   43_239
16                    432.5    1.0   0.0           1.0          6.0   45_144
17        369.3333333333333    1.0   0.0           1.0          6.0   45_148
18        331.6666666666667    1.0   0.0           1.0          6.0   45_231
19                   1395.0    1.0   0.0           1.0          6.0   45_232
20        535.3333333333334    1.0   0.0           1.0          6.0    48_50
21                 975.3125    1.0   0.0           1.0          6.0    48_68
22                   1706.0    1.0   0.0           1.0          6.0   48_100
23                    586.1    1.0   0.0           1.0          6.0   48_142
24        677.6666666666666    1.0   0.0           1.0          6.0   48_246
25        557.7878787878788    1.0   0.0           1.0          6.0    50_48
26                    364.3    1.0   0.0           1.0          6.0   50_143
27                    544.4    1.0   0.0           1.0          6.0   50_246
28        873.9756097560976    1.0   0.0           1.0          6.0    68_48
29       494.05555555555554    1.0   0.0           1.0          6.0    68_90
...                     ...    ...   ...           ...          ...      ...
1699296             262.579   12.0  23.0          31.0          6.0  237_141
1699297             264.667   12.0  23.0          31.0          6.0  237_162
1699298             312.333   12.0  23.0          31.0          6.0  237_163
1699299             303.188   12.0  23.0          31.0          6.0  237_236
1699300             292.143   12.0  23.0          31.0          6.0   238_43
1699301             230.511   12.0  23.0          31.0          6.0  238_151
1699302             249.308   12.0  23.0          31.0          6.0  238_239
1699303               308.1   12.0  23.0          31.0          6.0   239_43
1699304             289.229   12.0  23.0          31.0          6.0  239_142
1699305             286.714   12.0  23.0          31.0          6.0  239_143
1699306             236.359   12.0  23.0          31.0          6.0  239_238
1699307             361.583   12.0  23.0          31.0          6.0   246_48
1699308               278.4   12.0  23.0          31.0          6.0   246_50
1699309               419.3   12.0  23.0          31.0          6.0   246_68
1699310                 340   12.0  23.0          31.0          6.0  246_158
1699311             346.625   12.0  23.0          31.0          6.0   249_68
1699312             321.882   12.0  23.0          31.0          6.0   249_90
1699313             284.875   12.0  23.0          31.0          6.0  249_113
1699314             388.667   12.0  23.0          31.0          6.0  249_114
1699315               274.2   12.0  23.0          31.0          6.0  249_125
1699316               319.4   12.0  23.0          31.0          6.0  249_158
1699317             283.333   12.0  23.0          31.0          6.0   261_13
1699318             316.333   12.0  23.0          31.0          6.0   261_87
1699319             192.333   12.0  23.0          31.0          6.0   261_88
1699320               382.2   12.0  23.0          31.0          6.0  261_231
1699321             293.667   12.0  23.0          31.0          6.0  262_140
1699322             180.444   12.0  23.0          31.0          6.0  262_263
1699323              222.76   12.0  23.0          31.0          6.0  263_141
1699324               209.8   12.0  23.0          31.0          6.0  263_236
1699325             219.765   12.0  23.0          31.0          6.0  263_262

[1699326 rows x 16 columns]>

In [138]:
neighbors_2017.head()

,Unnamed: 0,time_block,PULocationID,DOLocationID,passenger_count,passenger_count.1,trip_distance,tip_amount,tolls_amount,total_amount,time_delta,month,hour,day_of_month,day_of_week,PU_DO
0,NaN,NaN,NaN,NaN,count,sum,mean,sum,sum,sum,mean,NaN,NaN,NaN,NaN,NaN
1,68.0,2017/01/01 00,4.0,79.0,18,39,0.7122222222222222,7.51,0.0,126.40999999999997,303.5,1.0,0.0,1.0,6.0,4_79
2,86.0,2017/01/01 00,4.0,224.0,3,4,0.7200000000000001,0.0,0.0,20.4,327.0,1.0,0.0,1.0,6.0,4_224
3,88.0,2017/01/01 00,4.0,232.0,4,11,1.2825000000000002,3.8,0.0,36.0,403.5,1.0,0.0,1.0,6.0,4_232
4,121.0,2017/01/01 00,13.0,231.0,8,17,1.12375,12.87,0.0,74.77,377.375,1.0,0.0,1.0,6.0,13_231

In [139]:
#keepcolumns=(1,2,3, 11,12, 13,14,15,16)
neighbors_2017=neighbors_2017.iloc[1:,]
neighbors_2017=neighbors_2017[['time_block', 'PU_DO', 'time_delta',  'month',  'hour',  'day_of_month',  'day_of_week'] ]

In [152]:
neighbors_2017.head

<bound method NDFrame.head of             time_block    PU_DO   time_delta  month  hour  day_of_month  \
1        2017/01/01 00     4_79   303.500000    1.0   0.0           1.0
2        2017/01/01 00    4_224   327.000000    1.0   0.0           1.0
3        2017/01/01 00    4_232   403.500000    1.0   0.0           1.0
4        2017/01/01 00   13_231   377.375000    1.0   0.0           1.0
5        2017/01/01 00   13_261   396.000000    1.0   0.0           1.0
6        2017/01/01 00    24_43   625.000000    1.0   0.0           1.0
7        2017/01/01 00   24_151   174.750000    1.0   0.0           1.0
8        2017/01/01 00    43_24   477.666667    1.0   0.0           1.0
9        2017/01/01 00   43_142   490.000000    1.0   0.0           1.0
10       2017/01/01 00   43_151   528.250000    1.0   0.0           1.0
11       2017/01/01 00   43_163   407.000000    1.0   0.0           1.0
12       2017/01/01 00   43_236   370.045455    1.0   0.0           1.0
13       2017/01/01 00   43_237   423.750000    1.0   0.0           1.0
14       2017/01/01 00   43_238   431.000000    1.0   0.0           1.0
15       2017/01/01 00   43_239   493.066667    1.0   0.0           1.0
16       2017/01/01 00   45_144   432.500000    1.0   0.0           1.0
17       2017/01/01 00   45_148   369.333333    1.0   0.0           1.0
18       2017/01/01 00   45_231   331.666667    1.0   0.0           1.0
19       2017/01/01 00   45_232  1395.000000    1.0   0.0           1.0
20       2017/01/01 00    48_50   535.333333    1.0   0.0           1.0
21       2017/01/01 00    48_68   975.312500    1.0   0.0           1.0
22       2017/01/01 00   48_100  1706.000000    1.0   0.0           1.0
23       2017/01/01 00   48_142   586.100000    1.0   0.0           1.0
24       2017/01/01 00   48_246   677.666667    1.0   0.0           1.0
25       2017/01/01 00    50_48   557.787879    1.0   0.0           1.0
26       2017/01/01 00   50_143   364.300000    1.0   0.0           1.0
27       2017/01/01 00   50_246   544.400000    1.0   0.0           1.0
28       2017/01/01 00    68_48   873.975610    1.0   0.0           1.0
29       2017/01/01 00    68_90   494.055556    1.0   0.0           1.0
30       2017/01/01 00   68_100   528.000000    1.0   0.0           1.0
...                ...      ...          ...    ...   ...           ...
1699296  2017/12/31 23  237_141   262.578947   12.0  23.0          31.0
1699297  2017/12/31 23  237_162   264.666667   12.0  23.0          31.0
1699298  2017/12/31 23  237_163   312.333333   12.0  23.0          31.0
1699299  2017/12/31 23  237_236   303.187500   12.0  23.0          31.0
1699300  2017/12/31 23   238_43   292.142857   12.0  23.0          31.0
1699301  2017/12/31 23  238_151   230.511111   12.0  23.0          31.0
1699302  2017/12/31 23  238_239   249.307692   12.0  23.0          31.0
1699303  2017/12/31 23   239_43   308.100000   12.0  23.0          31.0
1699304  2017/12/31 23  239_142   289.228571   12.0  23.0          31.0
1699305  2017/12/31 23  239_143   286.714286   12.0  23.0          31.0
1699306  2017/12/31 23  239_238   236.358974   12.0  23.0          31.0
1699307  2017/12/31 23   246_48   361.583333   12.0  23.0          31.0
1699308  2017/12/31 23   246_50   278.400000   12.0  23.0          31.0
1699309  2017/12/31 23   246_68   419.300000   12.0  23.0          31.0
1699310  2017/12/31 23  246_158   340.000000   12.0  23.0          31.0
1699311  2017/12/31 23   249_68   346.625000   12.0  23.0          31.0
1699312  2017/12/31 23   249_90   321.882353   12.0  23.0          31.0
1699313  2017/12/31 23  249_113   284.875000   12.0  23.0          31.0
1699314  2017/12/31 23  249_114   388.666667   12.0  23.0          31.0
1699315  2017/12/31 23  249_125   274.200000   12.0  23.0          31.0
1699316  2017/12/31 23  249_158   319.400000   12.0  23.0          31.0
1699317  2017/12/31 23   261_13   283.333333   12.0  23.0          31.0
1699318  2017/12/31 23   261_87   316.333333   12.0  23.0          31.0
1699319  2017/12/31 23   261_88   192.333333   12.0  23.0          31.0
1699320  2017/12/31 23  261_231   382.200000   12.0  23.0          31.0
1699321  2017/12/31 23  262_140   293.666667   12.0  23.0          31.0
1699322  2017/12/31 23  262_263   180.444444   12.0  23.0          31.0
1699323  2017/12/31 23  263_141   222.760000   12.0  23.0          31.0
1699324  2017/12/31 23  263_236   209.800000   12.0  23.0          31.0
1699325  2017/12/31 23  263_262   219.764706   12.0  23.0          31.0

         day_of_week
1                6.0
2                6.0
3                6.0
4                6.0
5                6.0
6                6.0
7                6.0
8                6.0
9                6.0
10               6.0
11               6.0
12               6.0
13               6.0
14               6.0
15               6.0
16               6.0
17               6.0
18               6.0
19               6.0
20               6.0
21               6.0
22               6.0
23               6.0
24               6.0
25               6.0
26               6.0
27               6.0
28               6.0
29               6.0
30               6.0
...              ...
1699296          6.0
1699297          6.0
1699298          6.0
1699299          6.0
1699300          6.0
1699301          6.0
1699302          6.0
1699303          6.0
1699304          6.0
1699305          6.0
1699306          6.0
1699307          6.0
1699308          6.0
1699309          6.0
1699310          6.0
1699311          6.0
1699312          6.0
1699313          6.0
1699314          6.0
1699315          6.0
1699316          6.0
1699317          6.0
1699318          6.0
1699319          6.0
1699320          6.0
1699321          6.0
1699322          6.0
1699323          6.0
1699324          6.0
1699325          6.0

[1699325 rows x 7 columns]>

In [141]:
neighbors_2017['time_delta']=pd.to_numeric(neighbors_2017['time_delta'])

In [142]:
zerodata2 = neighbors_2017.groupby(['time_block', 'PU_DO']).sum().unstack(fill_value=0).stack()

In [156]:
zerodata2.head

<bound method NDFrame.head of                         time_delta  month  hour  day_of_month  day_of_week
time_block    PU_DO
2017/01/01 00 100_164   554.500000    1.0   0.0           1.0          6.0
              100_186   622.000000    1.0   0.0           1.0          6.0
              100_230   773.000000    1.0   0.0           1.0          6.0
              100_48   1035.500000    1.0   0.0           1.0          6.0
              100_68    631.600000    1.0   0.0           1.0          6.0
              107_137   413.625000    1.0   0.0           1.0          6.0
              107_170   427.577778    1.0   0.0           1.0          6.0
              107_224   657.750000    1.0   0.0           1.0          6.0
              107_234   414.900000    1.0   0.0           1.0          6.0
              107_79    448.619048    1.0   0.0           1.0          6.0
              113_114   300.750000    1.0   0.0           1.0          6.0
              113_234   542.833333    1.0   0.0           1.0          6.0
              113_249   357.800000    1.0   0.0           1.0          6.0
              113_79    426.071429    1.0   0.0           1.0          6.0
              114_113   297.916667    1.0   0.0           1.0          6.0
              114_125   221.000000    1.0   0.0           1.0          6.0
              114_144   356.000000    1.0   0.0           1.0          6.0
              114_211   363.333333    1.0   0.0           1.0          6.0
              114_249   473.105263    1.0   0.0           1.0          6.0
              114_79    502.916667    1.0   0.0           1.0          6.0
              125_114     0.000000    0.0   0.0           0.0          0.0
              125_158   221.000000    1.0   0.0           1.0          6.0
              125_211     0.000000    0.0   0.0           0.0          0.0
              125_231   535.000000    1.0   0.0           1.0          6.0
              125_249   290.250000    1.0   0.0           1.0          6.0
              12_13       0.000000    0.0   0.0           0.0          0.0
              12_261      0.000000    0.0   0.0           0.0          0.0
              12_88       0.000000    0.0   0.0           0.0          0.0
              137_107   358.733333    1.0   0.0           1.0          6.0
              137_170   381.250000    1.0   0.0           1.0          6.0
...                            ...    ...   ...           ...          ...
2017/12/31 23 48_68     787.080000   12.0  23.0          31.0          6.0
              4_224     199.000000   12.0  23.0          31.0          6.0
              4_232     376.000000   12.0  23.0          31.0          6.0
              4_79      351.500000   12.0  23.0          31.0          6.0
              50_143    233.666667   12.0  23.0          31.0          6.0
              50_246    321.000000   12.0  23.0          31.0          6.0
              50_48     444.321429   12.0  23.0          31.0          6.0
              68_100    767.000000   12.0  23.0          31.0          6.0
              68_158    445.000000   12.0  23.0          31.0          6.0
              68_186    450.750000   12.0  23.0          31.0          6.0
              68_246    266.900000   12.0  23.0          31.0          6.0
              68_249    409.769231   12.0  23.0          31.0          6.0
              68_48     581.764706   12.0  23.0          31.0          6.0
              68_90     220.750000   12.0  23.0          31.0          6.0
              79_107    306.300000   12.0  23.0          31.0          6.0
              79_113    324.888889   12.0  23.0          31.0          6.0
              79_114    343.166667   12.0  23.0          31.0          6.0
              79_148    371.764706   12.0  23.0          31.0          6.0
              79_224    222.833333   12.0  23.0          31.0          6.0
              79_4      283.647059   12.0  23.0          31.0          6.0
              87_209    224.750000   12.0  23.0          31.0          6.0
              87_261    383.000000   12.0  23.0          31.0          6.0
              87_88     149.500000   12.0  23.0          31.0          6.0
              88_12       0.000000    0.0   0.0           0.0          0.0
              88_261      0.000000    0.0   0.0           0.0          0.0
              88_87     145.000000   12.0  23.0          31.0          6.0
              90_186    356.500000   12.0  23.0          31.0          6.0
              90_234    279.100000   12.0  23.0          31.0          6.0
              90_249    245.428571   12.0  23.0          31.0          6.0
              90_68     324.000000   12.0  23.0          31.0          6.0

[1997052 rows x 5 columns]>

In [144]:
zerodata2.to_csv('neighbors_data_2017_fixed_with_zeros.csv', encoding='utf-8')

In [145]:
zerodata3= pd.read_csv('neighbors_data_2017_fixed_with_zeros.csv')

In [150]:
zerodata3.head

<bound method NDFrame.head of             time_block    PU_DO   time_delta month hour day_of_month  \
0        2017/01/01 00  100_164   554.500000    01   00           01
1        2017/01/01 00  100_186   622.000000    01   00           01
2        2017/01/01 00  100_230   773.000000    01   00           01
3        2017/01/01 00   100_48  1035.500000    01   00           01
4        2017/01/01 00   100_68   631.600000    01   00           01
5        2017/01/01 00  107_137   413.625000    01   00           01
6        2017/01/01 00  107_170   427.577778    01   00           01
7        2017/01/01 00  107_224   657.750000    01   00           01
8        2017/01/01 00  107_234   414.900000    01   00           01
9        2017/01/01 00   107_79   448.619048    01   00           01
10       2017/01/01 00  113_114   300.750000    01   00           01
11       2017/01/01 00  113_234   542.833333    01   00           01
12       2017/01/01 00  113_249   357.800000    01   00           01
13       2017/01/01 00   113_79   426.071429    01   00           01
14       2017/01/01 00  114_113   297.916667    01   00           01
15       2017/01/01 00  114_125   221.000000    01   00           01
16       2017/01/01 00  114_144   356.000000    01   00           01
17       2017/01/01 00  114_211   363.333333    01   00           01
18       2017/01/01 00  114_249   473.105263    01   00           01
19       2017/01/01 00   114_79   502.916667    01   00           01
20       2017/01/01 00  125_114     0.000000    01   00           01
21       2017/01/01 00  125_158   221.000000    01   00           01
22       2017/01/01 00  125_211     0.000000    01   00           01
23       2017/01/01 00  125_231   535.000000    01   00           01
24       2017/01/01 00  125_249   290.250000    01   00           01
25       2017/01/01 00    12_13     0.000000    01   00           01
26       2017/01/01 00   12_261     0.000000    01   00           01
27       2017/01/01 00    12_88     0.000000    01   00           01
28       2017/01/01 00  137_107   358.733333    01   00           01
29       2017/01/01 00  137_170   381.250000    01   00           01
...                ...      ...          ...   ...  ...          ...
1997022  2017/12/31 23    48_68   787.080000    12   23           31
1997023  2017/12/31 23    4_224   199.000000    12   23           31
1997024  2017/12/31 23    4_232   376.000000    12   23           31
1997025  2017/12/31 23     4_79   351.500000    12   23           31
1997026  2017/12/31 23   50_143   233.666667    12   23           31
1997027  2017/12/31 23   50_246   321.000000    12   23           31
1997028  2017/12/31 23    50_48   444.321429    12   23           31
1997029  2017/12/31 23   68_100   767.000000    12   23           31
1997030  2017/12/31 23   68_158   445.000000    12   23           31
1997031  2017/12/31 23   68_186   450.750000    12   23           31
1997032  2017/12/31 23   68_246   266.900000    12   23           31
1997033  2017/12/31 23   68_249   409.769231    12   23           31
1997034  2017/12/31 23    68_48   581.764706    12   23           31
1997035  2017/12/31 23    68_90   220.750000    12   23           31
1997036  2017/12/31 23   79_107   306.300000    12   23           31
1997037  2017/12/31 23   79_113   324.888889    12   23           31
1997038  2017/12/31 23   79_114   343.166667    12   23           31
1997039  2017/12/31 23   79_148   371.764706    12   23           31
1997040  2017/12/31 23   79_224   222.833333    12   23           31
1997041  2017/12/31 23     79_4   283.647059    12   23           31
1997042  2017/12/31 23   87_209   224.750000    12   23           31
1997043  2017/12/31 23   87_261   383.000000    12   23           31
1997044  2017/12/31 23    87_88   149.500000    12   23           31
1997045  2017/12/31 23    88_12     0.000000    12   23           31
1997046  2017/12/31 23   88_261     0.000000    12   23           31
1997047  2017/12/31 23    88_87   145.000000    12   23           31
1997048  2017/12/31 23   90_186   356.500000    12   23           31
1997049  2017/12/31 23   90_234   279.100000    12   23           31
1997050  2017/12/31 23   90_249   245.428571    12   23           31
1997051  2017/12/31 23    90_68   324.000000    12   23           31

         day_of_week
0                6.0
1                6.0
2                6.0
3                6.0
4                6.0
5                6.0
6                6.0
7                6.0
8                6.0
9                6.0
10               6.0
11               6.0
12               6.0
13               6.0
14               6.0
15               6.0
16               6.0
17               6.0
18               6.0
19               6.0
20               0.0
21               6.0
22               0.0
23               6.0
24               6.0
25               0.0
26               0.0
27               0.0
28               6.0
29               6.0
...              ...
1997022          6.0
1997023          6.0
1997024          6.0
1997025          6.0
1997026          6.0
1997027          6.0
1997028          6.0
1997029          6.0
1997030          6.0
1997031          6.0
1997032          6.0
1997033          6.0
1997034          6.0
1997035          6.0
1997036          6.0
1997037          6.0
1997038          6.0
1997039          6.0
1997040          6.0
1997041          6.0
1997042          6.0
1997043          6.0
1997044          6.0
1997045          0.0
1997046          0.0
1997047          6.0
1997048          6.0
1997049          6.0
1997050          6.0
1997051          6.0

[1997052 rows x 7 columns]>

In [146]:
___, month, day_of_month, hour = zip(*zerodata3['time_block'].apply(lambda x: x.replace(' ','/').split('/')))

In [148]:
month = list(month)
hour = list(hour)
day_of_month = list(day_of_month)

zerodata3['month'] = month
zerodata3['hour'] = hour
zerodata3['day_of_month'] = day_of_month

In [151]:
from datetime import datetime as dt

dow = zerodata3['time_block'].apply(lambda x: dt.strptime(x, '%Y/%m/%d %H').weekday())
#display(adj_grouping_for_2017.head()['time_block'].apply(lambda x: dt.strptime(x, '%Y/%m/%d %H')))
zerodata3['day_of_week'] = dow

In [153]:
zerodata3.head

<bound method NDFrame.head of             time_block    PU_DO   time_delta month hour day_of_month  \
0        2017/01/01 00  100_164   554.500000    01   00           01
1        2017/01/01 00  100_186   622.000000    01   00           01
2        2017/01/01 00  100_230   773.000000    01   00           01
3        2017/01/01 00   100_48  1035.500000    01   00           01
4        2017/01/01 00   100_68   631.600000    01   00           01
5        2017/01/01 00  107_137   413.625000    01   00           01
6        2017/01/01 00  107_170   427.577778    01   00           01
7        2017/01/01 00  107_224   657.750000    01   00           01
8        2017/01/01 00  107_234   414.900000    01   00           01
9        2017/01/01 00   107_79   448.619048    01   00           01
10       2017/01/01 00  113_114   300.750000    01   00           01
11       2017/01/01 00  113_234   542.833333    01   00           01
12       2017/01/01 00  113_249   357.800000    01   00           01
13       2017/01/01 00   113_79   426.071429    01   00           01
14       2017/01/01 00  114_113   297.916667    01   00           01
15       2017/01/01 00  114_125   221.000000    01   00           01
16       2017/01/01 00  114_144   356.000000    01   00           01
17       2017/01/01 00  114_211   363.333333    01   00           01
18       2017/01/01 00  114_249   473.105263    01   00           01
19       2017/01/01 00   114_79   502.916667    01   00           01
20       2017/01/01 00  125_114     0.000000    01   00           01
21       2017/01/01 00  125_158   221.000000    01   00           01
22       2017/01/01 00  125_211     0.000000    01   00           01
23       2017/01/01 00  125_231   535.000000    01   00           01
24       2017/01/01 00  125_249   290.250000    01   00           01
25       2017/01/01 00    12_13     0.000000    01   00           01
26       2017/01/01 00   12_261     0.000000    01   00           01
27       2017/01/01 00    12_88     0.000000    01   00           01
28       2017/01/01 00  137_107   358.733333    01   00           01
29       2017/01/01 00  137_170   381.250000    01   00           01
...                ...      ...          ...   ...  ...          ...
1997022  2017/12/31 23    48_68   787.080000    12   23           31
1997023  2017/12/31 23    4_224   199.000000    12   23           31
1997024  2017/12/31 23    4_232   376.000000    12   23           31
1997025  2017/12/31 23     4_79   351.500000    12   23           31
1997026  2017/12/31 23   50_143   233.666667    12   23           31
1997027  2017/12/31 23   50_246   321.000000    12   23           31
1997028  2017/12/31 23    50_48   444.321429    12   23           31
1997029  2017/12/31 23   68_100   767.000000    12   23           31
1997030  2017/12/31 23   68_158   445.000000    12   23           31
1997031  2017/12/31 23   68_186   450.750000    12   23           31
1997032  2017/12/31 23   68_246   266.900000    12   23           31
1997033  2017/12/31 23   68_249   409.769231    12   23           31
1997034  2017/12/31 23    68_48   581.764706    12   23           31
1997035  2017/12/31 23    68_90   220.750000    12   23           31
1997036  2017/12/31 23   79_107   306.300000    12   23           31
1997037  2017/12/31 23   79_113   324.888889    12   23           31
1997038  2017/12/31 23   79_114   343.166667    12   23           31
1997039  2017/12/31 23   79_148   371.764706    12   23           31
1997040  2017/12/31 23   79_224   222.833333    12   23           31
1997041  2017/12/31 23     79_4   283.647059    12   23           31
1997042  2017/12/31 23   87_209   224.750000    12   23           31
1997043  2017/12/31 23   87_261   383.000000    12   23           31
1997044  2017/12/31 23    87_88   149.500000    12   23           31
1997045  2017/12/31 23    88_12     0.000000    12   23           31
1997046  2017/12/31 23   88_261     0.000000    12   23           31
1997047  2017/12/31 23    88_87   145.000000    12   23           31
1997048  2017/12/31 23   90_186   356.500000    12   23           31
1997049  2017/12/31 23   90_234   279.100000    12   23           31
1997050  2017/12/31 23   90_249   245.428571    12   23           31
1997051  2017/12/31 23    90_68   324.000000    12   23           31

         day_of_week
0                  6
1                  6
2                  6
3                  6
4                  6
5                  6
6                  6
7                  6
8                  6
9                  6
10                 6
11                 6
12                 6
13                 6
14                 6
15                 6
16                 6
17                 6
18                 6
19                 6
20                 6
21                 6
22                 6
23                 6
24                 6
25                 6
26                 6
27                 6
28                 6
29                 6
...              ...
1997022            6
1997023            6
1997024            6
1997025            6
1997026            6
1997027            6
1997028            6
1997029            6
1997030            6
1997031            6
1997032            6
1997033            6
1997034            6
1997035            6
1997036            6
1997037            6
1997038            6
1997039            6
1997040            6
1997041            6
1997042            6
1997043            6
1997044            6
1997045            6
1997046            6
1997047            6
1997048            6
1997049            6
1997050            6
1997051            6

[1997052 rows x 7 columns]>

In [174]:
zerodata3.to_csv('neighbors_data_2017_fixed_with_zeros.csv', encoding='utf-8')

In [157]:
zerodata3['time_block'].nunique()

8759

In [ ]:
#Should be 8760, from here, manually checked that no neighbor rides were taken on March 12th between 2-3AM, so added zeros to 
##each neighbor, 228 rows, for that hour