In [27]:
#This takes in the date/time/hour/zip data and creates seperates feasutres 

import pandas as pd
import numpy as np
from datetime import datetime, date, time

In [28]:
df = pd.read_csv('demand_data', index_col='time_block')

In [29]:
df.head

<bound method NDFrame.head of                Unnamed: 0  pickup_zip passenger_count passenger_count.1  \
time_block
NaN                   NaN         NaN           count               sum
0.0                   0.0         0.0          233691               0.0
2016/01/01 00         1.0     10001.0            2908            5372.0
2016/01/01 00         2.0     10002.0            2140            4068.0
2016/01/01 00         3.0     10003.0            3106            5734.0
2016/01/01 00         4.0     10004.0              18              40.0
2016/01/01 00         5.0     10005.0             236             460.0
2016/01/01 00         6.0     10006.0             176             324.0
2016/01/01 00         7.0     10007.0             318             588.0
2016/01/01 00         8.0     10009.0            1662            3020.0
2016/01/01 00         9.0     10011.0            3410            6102.0
2016/01/01 00        10.0     10012.0            1986            3808.0
2016/01/01 00        11.0     10013.0             490             926.0
2016/01/01 00        12.0     10014.0            1276            2194.0
2016/01/01 00        13.0     10016.0             860            1594.0
2016/01/01 00        14.0     10017.0            1506            2698.0
2016/01/01 00        15.0     10018.0            1576            2846.0
2016/01/01 00        16.0     10019.0            1646            3008.0
2016/01/01 00        17.0     10020.0             234             458.0
2016/01/01 00        18.0     10021.0            2340            4312.0
2016/01/01 00        19.0     10022.0            1056            1952.0
2016/01/01 00        20.0     10023.0            2030            3750.0
2016/01/01 00        21.0     10024.0               6              16.0
2016/01/01 00        22.0     10025.0             788            1400.0
2016/01/01 00        23.0     10028.0            2322            4128.0
2016/01/01 00        24.0     10038.0             132             222.0
2016/01/01 01        25.0     10001.0            2934            5524.0
2016/01/01 01        26.0     10002.0            2610            4890.0
2016/01/01 01        27.0     10003.0            2494            4448.0
2016/01/01 01        28.0     10004.0              14              22.0
...                   ...         ...             ...               ...
2016/06/30 22     68351.0     10022.0             352               569
2016/06/30 22     68352.0     10023.0             558               892
2016/06/30 22     68353.0     10024.0               4                11
2016/06/30 22     68354.0     10025.0             159               274
2016/06/30 22     68355.0     10028.0             515               832
2016/06/30 22     68356.0     10038.0              57                87
2016/06/30 23     68357.0     10001.0            1510              2515
2016/06/30 23     68358.0     10002.0            1016              1672
2016/06/30 23     68359.0     10003.0            1181              1979
2016/06/30 23     68360.0     10004.0               5                 6
2016/06/30 23     68361.0     10005.0             137               209
2016/06/30 23     68362.0     10006.0             102               133
2016/06/30 23     68363.0     10007.0             165               258
2016/06/30 23     68364.0     10009.0             547               894
2016/06/30 23     68365.0     10011.0            1212              1930
2016/06/30 23     68366.0     10012.0            1038              1762
2016/06/30 23     68367.0     10013.0             315               580
2016/06/30 23     68368.0     10014.0             436               714
2016/06/30 23     68369.0     10016.0             273               470
2016/06/30 23     68370.0     10017.0             737              1261
2016/06/30 23     68371.0     10018.0            1050              1768
2016/06/30 23     68372.0     10019.0             477               844
2016/06/30 23     68373.0     10020.0             440               737
2016/06/30 23     68374.0     10021.0             424               714
2016/06/30 23     68375.0     10022.0             281               458
2016/06/30 23     68376.0     10023.0             410               685
2016/06/30 23     68377.0     10024.0               4                 8
2016/06/30 23     68378.0     10025.0             120               187
2016/06/30 23     68379.0     10028.0             402               643
2016/06/30 23     68380.0     10038.0              36                61

                       tip_amount        tolls_amount        total_amount
time_block
NaN                           sum                 sum                 sum
0.0                           0.0                 0.0                 0.0
2016/01/01 00              4269.3  474.35999999999996   43727.05999999995
2016/01/01 00  3598.8599999999997               32.32  32864.979999999974
2016/01/01 00   4969.119999999998  222.30000000000007   44821.21999999997
2016/01/01 00                 4.0                 0.0  242.39999999999998
2016/01/01 00   497.2799999999999               11.08   4569.160000000002
2016/01/01 00  398.56000000000006               33.24              3307.6
2016/01/01 00  489.61999999999995                 0.0             5122.02
2016/01/01 00  3073.3199999999983               82.64  24190.559999999998
2016/01/01 00   5409.459999999998   297.9200000000001   50558.47999999999
2016/01/01 00  3176.1600000000003   87.47999999999999   30759.43999999997
2016/01/01 00   893.2600000000001               33.24   8189.500000000003
2016/01/01 00  2095.1800000000003               93.72   20338.69999999999
2016/01/01 00             1203.08               93.72  11836.800000000007
2016/01/01 00  1979.5799999999995              326.32  21189.699999999997
2016/01/01 00  2014.1200000000008  330.12000000000006   28106.63999999996
2016/01/01 00             2641.48               66.48  28137.759999999977
2016/01/01 00  200.70000000000002               16.16   4068.859999999998
2016/01/01 00  2922.5200000000004   75.47999999999999  30238.799999999967
2016/01/01 00             1210.68  53.839999999999996  13266.320000000005
2016/01/01 00   2894.799999999999               82.64   28407.23999999997
2016/01/01 00                 2.0                 0.0   77.80000000000001
2016/01/01 00  1272.9399999999998              115.88  12534.020000000004
2016/01/01 00  3360.5999999999995               99.72  31652.519999999964
2016/01/01 00              196.32               11.08  2018.7999999999997
2016/01/01 01   4709.779999999996  457.03999999999996  43578.819999999956
2016/01/01 01             5078.06  168.88000000000002   46667.55999999993
2016/01/01 01  4084.0800000000004  231.76000000000008   37655.65999999997
2016/01/01 01               19.52                 0.0              198.72
...                           ...                 ...                 ...
2016/06/30 22              565.44                8.08             4958.62
2016/06/30 22              910.48               30.24             7780.62
2016/06/30 22               10.37                   0               83.02
2016/06/30 22              237.99               19.16             2294.85
2016/06/30 22              876.88               44.32             7546.95
2016/06/30 22              165.56                5.54             1297.65
2016/06/30 23                2706              185.36             23465.3
2016/06/30 23             2031.75                24.7             17085.3
2016/06/30 23             2241.66               66.48             18281.6
2016/06/30 23                8.55                   0              109.05
2016/06/30 23              449.93               38.78             3464.81
2016/06/30 23               313.8                27.7              2634.1
2016/06/30 23              372.36                7.62             3170.98
2016/06/30 23             1027.26               49.86             8588.22
2016/06/30 23             2333.66              185.62             19358.7
2016/06/30 23             1958.97               73.86             16540.6
2016/06/30 23              722.81               27.12             5887.38
2016/06/30 23              813.54               41.32             7087.11
2016/06/30 23              438.88                27.7             4215.48
2016/06/30 23             1436.13               131.8               11584
2016/06/30 23             1864.56              141.76             16236.3
2016/06/30 23              795.34               35.78             6901.67
2016/06/30 23              696.59               54.24             6577.28
2016/06/30 23              648.12                38.2             5997.02
2016/06/30 23              478.58               33.24             4183.12
2016/06/30 23              662.44               32.24             5745.63
2016/06/30 23                3.41                   0               61.11
2016/06/30 23              164.56               13.62             1747.28
2016/06/30 23              608.47               34.66             5518.23
2016/06/30 23               94.14                   0              753.94

[68382 rows x 7 columns]>

In [30]:
# First, remove the first row as its weird
df = df.drop(index = '0.0')
df = df.dropna()

In [31]:
df

,Unnamed: 0,pickup_zip,passenger_count,passenger_count.1,tip_amount,tolls_amount,total_amount
time_block,,,,,,,
2016/01/01 00,1.0,10001.0,2908,5372.0,4269.3,474.35999999999996,43727.05999999995
2016/01/01 00,2.0,10002.0,2140,4068.0,3598.8599999999997,32.32,32864.979999999974
2016/01/01 00,3.0,10003.0,3106,5734.0,4969.119999999998,222.30000000000007,44821.21999999997
2016/01/01 00,4.0,10004.0,18,40.0,4.0,0.0,242.39999999999998
2016/01/01 00,5.0,10005.0,236,460.0,497.2799999999999,11.08,4569.160000000002
2016/01/01 00,6.0,10006.0,176,324.0,398.56000000000006,33.24,3307.6
2016/01/01 00,7.0,10007.0,318,588.0,489.61999999999995,0.0,5122.02
2016/01/01 00,8.0,10009.0,1662,3020.0,3073.3199999999983,82.64,24190.559999999998
2016/01/01 00,9.0,10011.0,3410,6102.0,5409.459999999998,297.9200000000001,50558.47999999999
2016/01/01 00,10.0,10012.0,1986,3808.0,3176.1600000000003,87.47999999999999,30759.43999999997
2016/01/01 00,11.0,10013.0,490,926.0,893.2600000000001,33.24,8189.500000000003
2016/01/01 00,12.0,10014.0,1276,2194.0,2095.1800000000003,93.72,20338.69999999999
2016/01/01 00,13.0,10016.0,860,1594.0,1203.08,93.72,11836.800000000007
2016/01/01 00,14.0,10017.0,1506,2698.0,1979.5799999999995,326.32,21189.699999999997
2016/01/01 00,15.0,10018.0,1576,2846.0,2014.1200000000008,330.12000000000006,28106.63999999996
2016/01/01 00,16.0,10019.0,1646,3008.0,2641.48,66.48,28137.759999999977
2016/01/01 00,17.0,10020.0,234,458.0,200.70000000000002,16.16,4068.859999999998
2016/01/01 00,18.0,10021.0,2340,4312.0,2922.5200000000004,75.47999999999999,30238.799999999967
2016/01/01 00,19.0,10022.0,1056,1952.0,1210.68,53.839999999999996,13266.320000000005
2016/01/01 00,20.0,10023.0,2030,3750.0,2894.799999999999,82.64,28407.23999999997
2016/01/01 00,21.0,10024.0,6,16.0,2.0,0.0,77.80000000000001
2016/01/01 00,22.0,10025.0,788,1400.0,1272.9399999999998,115.88,12534.020000000004
2016/01/01 00,23.0,10028.0,2322,4128.0,3360.5999999999995,99.72,31652.519999999964
2016/01/01 00,24.0,10038.0,132,222.0,196.32,11.08,2018.7999999999997
2016/01/01 01,25.0,10001.0,2934,5524.0,4709.779999999996,457.03999999999996,43578.819999999956
2016/01/01 01,26.0,10002.0,2610,4890.0,5078.06,168.88000000000002,46667.55999999993
2016/01/01 01,27.0,10003.0,2494,4448.0,4084.0800000000004,231.76000000000008,37655.65999999997
2016/01/01 01,28.0,10004.0,14,22.0,19.52,0.0,198.72
2016/01/01 01,29.0,10005.0,360,630.0,623.14,33.24,7171.380000000006
2016/01/01 01,30.0,10006.0,278,524.0,652.5400000000002,66.48,6035.420000000004
...,...,...,...,...,...,...,...
2016/06/30 22,68351.0,10022.0,352,569,565.44,8.08,4958.62
2016/06/30 22,68352.0,10023.0,558,892,910.48,30.24,7780.62
2016/06/30 22,68353.0,10024.0,4,11,10.37,0,83.02
2016/06/30 22,68354.0,10025.0,159,274,237.99,19.16,2294.85
2016/06/30 22,68355.0,10028.0,515,832,876.88,44.32,7546.95
2016/06/30 22,68356.0,10038.0,57,87,165.56,5.54,1297.65
2016/06/30 23,68357.0,10001.0,1510,2515,2706,185.36,23465.3
2016/06/30 23,68358.0,10002.0,1016,1672,2031.75,24.7,17085.3
2016/06/30 23,68359.0,10003.0,1181,1979,2241.66,66.48,18281.6
2016/06/30 23,68360.0,10004.0,5,6,8.55,0,109.05
2016/06/30 23,68361.0,10005.0,137,209,449.93,38.78,3464.81
2016/06/30 23,68362.0,10006.0,102,133,313.8,27.7,2634.1
2016/06/30 23,68363.0,10007.0,165,258,372.36,7.62,3170.98
2016/06/30 23,68364.0,10009.0,547,894,1027.26,49.86,8588.22
2016/06/30 23,68365.0,10011.0,1212,1930,2333.66,185.62,19358.7
2016/06/30 23,68366.0,10012.0,1038,1762,1958.97,73.86,16540.6
2016/06/30 23,68367.0,10013.0,315,580,722.81,27.12,5887.38
2016/06/30 23,68368.0,10014.0,436,714,813.54,41.32,7087.11
2016/06/30 23,68369.0,10016.0,273,470,438.88,27.7,4215.48
2016/06/30 23,68370.0,10017.0,737,1261,1436.13,131.8,11584
2016/06/30 23,68371.0,10018.0,1050,1768,1864.56,141.76,16236.3
2016/06/30 23,68372.0,10019.0,477,844,795.34,35.78,6901.67
2016/06/30 23,68373.0,10020.0,440,737,696.59,54.24,6577.28
2016/06/30 23,68374.0,10021.0,424,714,648.12,38.2,5997.02
2016/06/30 23,68375.0,10022.0,281,458,478.58,33.24,4183.12
2016/06/30 23,68376.0,10023.0,410,685,662.44,32.24,5745.63
2016/06/30 23,68377.0,10024.0,4,8,3.41,0,61.11
2016/06/30 23,68378.0,10025.0,120,187,164.56,13.62,1747.28
2016/06/30 23,68379.0,10028.0,402,643,608.47,34.66,5518.23
2016/06/30 23,68380.0,10038.0,36,61,94.14,0,753.94

In [106]:
#First, Isolate the Hour
blocks = df.index
Hours = [0] * len(df)
Days = [0] * len(df)
Days_o_week = [0] * len(df)
Months = [0] * len(df)

for i in range(len(df)):
    #Get the Hours
    current_block = blocks[i]
    Hour = current_block[-2:]
    Hours[i] = int(Hour)
    
    #Get the Dates
    date = current_block[:10]
    date = datetime.strptime(date, '%Y/%m/%d')
    
    Days[i] = date.day
    Days_o_week[i] = date.weekday()
    Months[i] = date.month
    
    
    

#Merge the Times into the Data frame
df['Hour'] = Hours
df['Day'] = Days
df['Day_of_week'] = Days_o_week
df['Month'] = Months
print(df)
print(type(df))

               Unnamed: 0  pickup_zip passenger_count passenger_count.1  \
time_block
2016/01/01 00         1.0     10001.0            2908            5372.0
2016/01/01 00         2.0     10002.0            2140            4068.0
2016/01/01 00         3.0     10003.0            3106            5734.0
2016/01/01 00         4.0     10004.0              18              40.0
2016/01/01 00         5.0     10005.0             236             460.0
2016/01/01 00         6.0     10006.0             176             324.0
2016/01/01 00         7.0     10007.0             318             588.0
2016/01/01 00         8.0     10009.0            1662            3020.0
2016/01/01 00         9.0     10011.0            3410            6102.0
2016/01/01 00        10.0     10012.0            1986            3808.0
2016/01/01 00        11.0     10013.0             490             926.0
2016/01/01 00        12.0     10014.0            1276            2194.0
2016/01/01 00        13.0     10016.0             860            1594.0
2016/01/01 00        14.0     10017.0            1506            2698.0
2016/01/01 00        15.0     10018.0            1576            2846.0
2016/01/01 00        16.0     10019.0            1646            3008.0
2016/01/01 00        17.0     10020.0             234             458.0
2016/01/01 00        18.0     10021.0            2340            4312.0
2016/01/01 00        19.0     10022.0            1056            1952.0
2016/01/01 00        20.0     10023.0            2030            3750.0
2016/01/01 00        21.0     10024.0               6              16.0
2016/01/01 00        22.0     10025.0             788            1400.0
2016/01/01 00        23.0     10028.0            2322            4128.0
2016/01/01 00        24.0     10038.0             132             222.0
2016/01/01 01        25.0     10001.0            2934            5524.0
2016/01/01 01        26.0     10002.0            2610            4890.0
2016/01/01 01        27.0     10003.0            2494            4448.0
2016/01/01 01        28.0     10004.0              14              22.0
2016/01/01 01        29.0     10005.0             360             630.0
2016/01/01 01        30.0     10006.0             278             524.0
...                   ...         ...             ...               ...
2016/06/30 22     68351.0     10022.0             352               569
2016/06/30 22     68352.0     10023.0             558               892
2016/06/30 22     68353.0     10024.0               4                11
2016/06/30 22     68354.0     10025.0             159               274
2016/06/30 22     68355.0     10028.0             515               832
2016/06/30 22     68356.0     10038.0              57                87
2016/06/30 23     68357.0     10001.0            1510              2515
2016/06/30 23     68358.0     10002.0            1016              1672
2016/06/30 23     68359.0     10003.0            1181              1979
2016/06/30 23     68360.0     10004.0               5                 6
2016/06/30 23     68361.0     10005.0             137               209
2016/06/30 23     68362.0     10006.0             102               133
2016/06/30 23     68363.0     10007.0             165               258
2016/06/30 23     68364.0     10009.0             547               894
2016/06/30 23     68365.0     10011.0            1212              1930
2016/06/30 23     68366.0     10012.0            1038              1762
2016/06/30 23     68367.0     10013.0             315               580
2016/06/30 23     68368.0     10014.0             436               714
2016/06/30 23     68369.0     10016.0             273               470
2016/06/30 23     68370.0     10017.0             737              1261
2016/06/30 23     68371.0     10018.0            1050              1768
2016/06/30 23     68372.0     10019.0             477               844
2016/06/30 23     68373.0     10020.0             440               737
2016/06/30 23     68374.0     10021.0             424               714
2016/06/30 23     68375.0     10022.0             281               458
2016/06/30 23     68376.0     10023.0             410               685
2016/06/30 23     68377.0     10024.0               4                 8
2016/06/30 23     68378.0     10025.0             120               187
2016/06/30 23     68379.0     10028.0             402               643
2016/06/30 23     68380.0     10038.0              36                61

                       tip_amount        tolls_amount        total_amount  \
time_block
2016/01/01 00              4269.3  474.35999999999996   43727.05999999995
2016/01/01 00  3598.8599999999997               32.32  32864.979999999974
2016/01/01 00   4969.119999999998  222.30000000000007   44821.21999999997
2016/01/01 00                 4.0                 0.0  242.39999999999998
2016/01/01 00   497.2799999999999               11.08   4569.160000000002
2016/01/01 00  398.56000000000006               33.24              3307.6
2016/01/01 00  489.61999999999995                 0.0             5122.02
2016/01/01 00  3073.3199999999983               82.64  24190.559999999998
2016/01/01 00   5409.459999999998   297.9200000000001   50558.47999999999
2016/01/01 00  3176.1600000000003   87.47999999999999   30759.43999999997
2016/01/01 00   893.2600000000001               33.24   8189.500000000003
2016/01/01 00  2095.1800000000003               93.72   20338.69999999999
2016/01/01 00             1203.08               93.72  11836.800000000007
2016/01/01 00  1979.5799999999995              326.32  21189.699999999997
2016/01/01 00  2014.1200000000008  330.12000000000006   28106.63999999996
2016/01/01 00             2641.48               66.48  28137.759999999977
2016/01/01 00  200.70000000000002               16.16   4068.859999999998
2016/01/01 00  2922.5200000000004   75.47999999999999  30238.799999999967
2016/01/01 00             1210.68  53.839999999999996  13266.320000000005
2016/01/01 00   2894.799999999999               82.64   28407.23999999997
2016/01/01 00                 2.0                 0.0   77.80000000000001
2016/01/01 00  1272.9399999999998              115.88  12534.020000000004
2016/01/01 00  3360.5999999999995               99.72  31652.519999999964
2016/01/01 00              196.32               11.08  2018.7999999999997
2016/01/01 01   4709.779999999996  457.03999999999996  43578.819999999956
2016/01/01 01             5078.06  168.88000000000002   46667.55999999993
2016/01/01 01  4084.0800000000004  231.76000000000008   37655.65999999997
2016/01/01 01               19.52                 0.0              198.72
2016/01/01 01              623.14               33.24   7171.380000000006
2016/01/01 01   652.5400000000002               66.48   6035.420000000004
...                           ...                 ...                 ...
2016/06/30 22              565.44                8.08             4958.62
2016/06/30 22              910.48               30.24             7780.62
2016/06/30 22               10.37                   0               83.02
2016/06/30 22              237.99               19.16             2294.85
2016/06/30 22              876.88               44.32             7546.95
2016/06/30 22              165.56                5.54             1297.65
2016/06/30 23                2706              185.36             23465.3
2016/06/30 23             2031.75                24.7             17085.3
2016/06/30 23             2241.66               66.48             18281.6
2016/06/30 23                8.55                   0              109.05
2016/06/30 23              449.93               38.78             3464.81
2016/06/30 23               313.8                27.7              2634.1
2016/06/30 23              372.36                7.62             3170.98
2016/06/30 23             1027.26               49.86             8588.22
2016/06/30 23             2333.66              185.62             19358.7
2016/06/30 23             1958.97               73.86             16540.6
2016/06/30 23              722.81               27.12             5887.38
2016/06/30 23              813.54               41.32             7087.11
2016/06/30 23              438.88                27.7             4215.48
2016/06/30 23             1436.13               131.8               11584
2016/06/30 23             1864.56              141.76             16236.3
2016/06/30 23              795.34               35.78             6901.67
2016/06/30 23              696.59               54.24             6577.28
2016/06/30 23              648.12                38.2             5997.02
2016/06/30 23              478.58               33.24             4183.12
2016/06/30 23              662.44               32.24             5745.63
2016/06/30 23                3.41                   0               61.11
2016/06/30 23              164.56               13.62             1747.28
2016/06/30 23              608.47               34.66             5518.23
2016/06/30 23               94.14                   0              753.94

               Hour  Day  Day_of_week  Month
time_block
2016/01/01 00     0    1            4      1
2016/01/01 00     0    1            4      1
2016/01/01 00     0    1            4      1
2016/01/01 00     0    1            4      1
2016/01/01 00     0    1            4      1
2016/01/01 00     0    1            4      1
2016/01/01 00     0    1            4      1
2016/01/01 00     0    1            4      1
2016/01/01 00     0    1            4      1
2016/01/01 00     0    1            4      1
2016/01/01 00     0    1            4      1
2016/01/01 00     0    1            4      1
2016/01/01 00     0    1            4      1
2016/01/01 00     0    1            4      1
2016/01/01 00     0    1            4      1
2016/01/01 00     0    1            4      1
2016/01/01 00     0    1            4      1
2016/01/01 00     0    1            4      1
2016/01/01 00     0    1            4      1
2016/01/01 00     0    1            4      1
2016/01/01 00     0    1            4      1
2016/01/01 00     0    1            4      1
2016/01/01 00     0    1            4      1
2016/01/01 00     0    1            4      1
2016/01/01 01     1    1            4      1
2016/01/01 01     1    1            4      1
2016/01/01 01     1    1            4      1
2016/01/01 01     1    1            4      1
2016/01/01 01     1    1            4      1
2016/01/01 01     1    1            4      1
...             ...  ...          ...    ...
2016/06/30 22    22   30            3      6
2016/06/30 22    22   30            3      6
2016/06/30 22    22   30            3      6
2016/06/30 22    22   30            3      6
2016/06/30 22    22   30            3      6
2016/06/30 22    22   30            3      6
2016/06/30 23    23   30            3      6
2016/06/30 23    23   30            3      6
2016/06/30 23    23   30            3      6
2016/06/30 23    23   30            3      6
2016/06/30 23    23   30            3      6
2016/06/30 23    23   30            3      6
2016/06/30 23    23   30            3      6
2016/06/30 23    23   30            3      6
2016/06/30 23    23   30            3      6
2016/06/30 23    23   30            3      6
2016/06/30 23    23   30            3      6
2016/06/30 23    23   30            3      6
2016/06/30 23    23   30            3      6
2016/06/30 23    23   30            3      6
2016/06/30 23    23   30            3      6
2016/06/30 23    23   30            3      6
2016/06/30 23    23   30            3      6
2016/06/30 23    23   30            3      6
2016/06/30 23    23   30            3      6
2016/06/30 23    23   30            3      6
2016/06/30 23    23   30            3      6
2016/06/30 23    23   30            3      6
2016/06/30 23    23   30            3      6
2016/06/30 23    23   30            3      6

[68380 rows x 11 columns]
<class 'pandas.core.frame.DataFrame'>

In [109]:
#Export to csv
df.to_csv('Demand_Data2.csv', sep=',')