In [59]:
import pandas as pd
from sklearn.linear_model import LinearRegression

In [71]:
demand_data = pd.read_csv("/Users/kentarohoffman/Documents/Github/Hoffman_Leinwand_COMP755_Project/Demand_Data2_2017.csv")
demand_data

,time_block,Unnamed: 0,PULocationID,passenger_count,passenger_count.1,tip_amount,tolls_amount,total_amount,Hour,Day,Day_of_week,Month
0,2017/01/01 00,70.0,4.0,135,260,188.94,0.00,2164.94,0,1,6,1
1,2017/01/01 00,71.0,12.0,3,4,0.00,0.00,47.40,0,1,6,1
2,2017/01/01 00,72.0,13.0,104,173,192.16,21.58,1917.44,0,1,6,1
3,2017/01/01 00,73.0,24.0,94,164,141.35,5.54,1409.09,0,1,6,1
4,2017/01/01 00,74.0,43.0,401,786,430.13,0.00,5560.93,0,1,6,1
5,2017/01/01 00,75.0,45.0,54,96,91.55,0.00,973.25,0,1,6,1
6,2017/01/01 00,76.0,48.0,697,1208,1080.89,167.80,14271.79,0,1,6,1
7,2017/01/01 00,77.0,50.0,315,533,543.72,32.66,5631.38,0,1,6,1
8,2017/01/01 00,78.0,68.0,664,1114,1247.39,139.41,12096.95,0,1,6,1
9,2017/01/01 00,79.0,79.0,1076,1870,1901.33,55.40,17158.38,0,1,6,1
10,2017/01/01 00,80.0,87.0,150,244,280.40,11.08,2856.48,0,1,6,1
11,2017/01/01 00,81.0,88.0,70,135,105.01,13.16,1386.67,0,1,6,1
12,2017/01/01 00,82.0,90.0,470,813,775.70,41.32,7600.02,0,1,6,1
13,2017/01/01 00,83.0,100.0,100,174,140.59,11.08,1739.17,0,1,6,1
14,2017/01/01 00,84.0,107.0,628,1125,1126.10,49.32,9662.12,0,1,6,1
15,2017/01/01 00,85.0,113.0,318,578,585.05,33.24,5314.09,0,1,6,1
16,2017/01/01 00,86.0,114.0,406,730,764.00,16.04,7025.69,0,1,6,1
17,2017/01/01 00,87.0,125.0,99,171,217.51,27.12,1933.83,0,1,6,1
18,2017/01/01 00,88.0,137.0,305,560,457.41,46.28,4587.15,0,1,6,1
19,2017/01/01 00,89.0,140.0,230,403,332.14,18.54,3130.63,0,1,6,1
20,2017/01/01 00,90.0,141.0,525,925,669.42,27.70,7243.52,0,1,6,1
21,2017/01/01 00,91.0,142.0,739,1312,1134.05,37.62,11877.27,0,1,6,1
22,2017/01/01 00,92.0,143.0,234,429,377.80,11.08,3525.48,0,1,6,1
23,2017/01/01 00,93.0,144.0,270,518,499.38,25.00,4416.33,0,1,6,1
24,2017/01/01 00,94.0,148.0,594,1012,1252.55,34.12,10422.02,0,1,6,1
25,2017/01/01 00,95.0,151.0,238,428,319.22,27.70,3580.72,0,1,6,1
26,2017/01/01 00,96.0,158.0,297,511,533.20,28.54,4981.19,0,1,6,1
27,2017/01/01 00,97.0,161.0,652,1185,781.47,93.02,10822.99,0,1,6,1
28,2017/01/01 00,98.0,162.0,416,708,563.97,54.82,6609.84,0,1,6,1
29,2017/01/01 00,99.0,163.0,222,415,281.95,5.54,3365.09,0,1,6,1
...,...,...,...,...,...,...,...,...,...,...,...,...
444720,2017/12/31 23,444790.0,142.0,387,709,481.61,5.28,4982.74,23,31,6,12
444721,2017/12/31 23,444791.0,143.0,84,160,101.59,0.00,987.19,23,31,6,12
444722,2017/12/31 23,444792.0,144.0,130,228,163.20,10.50,1628.20,23,31,6,12
444723,2017/12/31 23,444793.0,148.0,197,314,289.44,10.50,2657.04,23,31,6,12
444724,2017/12/31 23,444794.0,151.0,123,206,145.28,0.00,1570.68,23,31,6,12
444725,2017/12/31 23,444795.0,158.0,161,281,254.92,16.26,2289.38,23,31,6,12
444726,2017/12/31 23,444796.0,161.0,249,452,233.88,25.04,3535.12,23,31,6,12
444727,2017/12/31 23,444797.0,162.0,273,460,206.97,11.52,3313.34,23,31,6,12
444728,2017/12/31 23,444798.0,163.0,127,199,171.98,5.76,1904.84,23,31,6,12
444729,2017/12/31 23,444799.0,164.0,205,359,302.88,23.04,2971.92,23,31,6,12
444730,2017/12/31 23,444800.0,170.0,211,364,279.34,33.54,2693.18,23,31,6,12
444731,2017/12/31 23,444801.0,186.0,212,376,255.64,17.28,3052.52,23,31,6,12
444732,2017/12/31 23,444802.0,209.0,25,34,37.03,0.00,360.53,23,31,6,12
444733,2017/12/31 23,444803.0,211.0,86,147,95.74,0.00,1100.99,23,31,6,12
444734,2017/12/31 23,444804.0,224.0,23,49,31.98,0.00,278.88,23,31,6,12
444735,2017/12/31 23,444805.0,229.0,202,334,220.62,17.28,2598.75,23,31,6,12
444736,2017/12/31 23,444806.0,230.0,119,233,124.10,0.00,1683.30,23,31,6,12
444737,2017/12/31 23,444807.0,231.0,151,264,199.38,10.50,2173.53,23,31,6,12
444738,2017/12/31 23,444808.0,232.0,32,62,47.50,0.00,469.10,23,31,6,12
444739,2017/12/31 23,444809.0,233.0,92,163,98.15,11.52,1173.27,23,31,6,12
444740,2017/12/31 23,444810.0,234.0,273,460,364.28,11.52,3588.15,23,31,6,12
444741,2017/12/31 23,444811.0,236.0,286,472,316.23,11.52,3439.50,23,31,6,12
444742,2017/12/31 23,444812.0,237.0,247,419,221.83,8.30,2613.73,23,31,6,12
444743,2017/12/31 23,444813.0,238.0,299,551,330.78,5.76,3386.19,23,31,6,12
444744,2017/12/31 23,444814.0,239.0,290,521,354.04,0.00,3239.04,23,31,6,12
444745,2017/12/31 23,444815.0,246.0,90,134,102.99,5.76,1142.75,23,31,6,12
444746,2017/12/31 23,444816.0,249.0,238,416,356.29,27.56,3228.25,23,31,6,12
444747,2017/12/31 23,444817.0,261.0,48,68,62.18,5.76,883.34,23,31,6,12
444748,2017/12/31 23,444818.0,262.0,103,188,131.68,2.64,1213.47,23,31,6,12
444749,2017/12/31 23,444819.0,263.0,256,438,322.36,5.76,3025.92,23,31,6,12

In [95]:
demand_data2 = demand_data
X = demand_data2['Hour'].values
dum = pd.get_dummies(X)
demand_data.assign(h0 = dum[0].tolist())
demand_data.assign(h1 = dum[0].tolist())
demand_data.assign(h2 = dum[0].tolist())
demand_data.assign(h3 = dum[0].tolist())
demand_data.assign(h4 = dum[0].tolist())
demand_data.assign(h5 = dum[0].tolist())
demand_data.assign(h6 = dum[0].tolist())
demand_data.assign(h7 = dum[0].tolist())
demand_data.assign(h8 = dum[0].tolist())
demand_data.assign(h9 = dum[0].tolist())
demand_data.assign(h10 = dum[0].tolist())
demand_data.assign(h11 = dum[0].tolist())
demand_data.assign(h12 = dum[0].tolist())

,time_block,Unnamed: 0,PULocationID,passenger_count,passenger_count.1,tip_amount,tolls_amount,total_amount,Hour,Day,Day_of_week,Month,h1
0,2017/01/01 00,70.0,4.0,135,260,188.94,0.00,2164.94,0,1,6,1,1
1,2017/01/01 00,71.0,12.0,3,4,0.00,0.00,47.40,0,1,6,1,1
2,2017/01/01 00,72.0,13.0,104,173,192.16,21.58,1917.44,0,1,6,1,1
3,2017/01/01 00,73.0,24.0,94,164,141.35,5.54,1409.09,0,1,6,1,1
4,2017/01/01 00,74.0,43.0,401,786,430.13,0.00,5560.93,0,1,6,1,1
5,2017/01/01 00,75.0,45.0,54,96,91.55,0.00,973.25,0,1,6,1,1
6,2017/01/01 00,76.0,48.0,697,1208,1080.89,167.80,14271.79,0,1,6,1,1
7,2017/01/01 00,77.0,50.0,315,533,543.72,32.66,5631.38,0,1,6,1,1
8,2017/01/01 00,78.0,68.0,664,1114,1247.39,139.41,12096.95,0,1,6,1,1
9,2017/01/01 00,79.0,79.0,1076,1870,1901.33,55.40,17158.38,0,1,6,1,1
10,2017/01/01 00,80.0,87.0,150,244,280.40,11.08,2856.48,0,1,6,1,1
11,2017/01/01 00,81.0,88.0,70,135,105.01,13.16,1386.67,0,1,6,1,1
12,2017/01/01 00,82.0,90.0,470,813,775.70,41.32,7600.02,0,1,6,1,1
13,2017/01/01 00,83.0,100.0,100,174,140.59,11.08,1739.17,0,1,6,1,1
14,2017/01/01 00,84.0,107.0,628,1125,1126.10,49.32,9662.12,0,1,6,1,1
15,2017/01/01 00,85.0,113.0,318,578,585.05,33.24,5314.09,0,1,6,1,1
16,2017/01/01 00,86.0,114.0,406,730,764.00,16.04,7025.69,0,1,6,1,1
17,2017/01/01 00,87.0,125.0,99,171,217.51,27.12,1933.83,0,1,6,1,1
18,2017/01/01 00,88.0,137.0,305,560,457.41,46.28,4587.15,0,1,6,1,1
19,2017/01/01 00,89.0,140.0,230,403,332.14,18.54,3130.63,0,1,6,1,1
20,2017/01/01 00,90.0,141.0,525,925,669.42,27.70,7243.52,0,1,6,1,1
21,2017/01/01 00,91.0,142.0,739,1312,1134.05,37.62,11877.27,0,1,6,1,1
22,2017/01/01 00,92.0,143.0,234,429,377.80,11.08,3525.48,0,1,6,1,1
23,2017/01/01 00,93.0,144.0,270,518,499.38,25.00,4416.33,0,1,6,1,1
24,2017/01/01 00,94.0,148.0,594,1012,1252.55,34.12,10422.02,0,1,6,1,1
25,2017/01/01 00,95.0,151.0,238,428,319.22,27.70,3580.72,0,1,6,1,1
26,2017/01/01 00,96.0,158.0,297,511,533.20,28.54,4981.19,0,1,6,1,1
27,2017/01/01 00,97.0,161.0,652,1185,781.47,93.02,10822.99,0,1,6,1,1
28,2017/01/01 00,98.0,162.0,416,708,563.97,54.82,6609.84,0,1,6,1,1
29,2017/01/01 00,99.0,163.0,222,415,281.95,5.54,3365.09,0,1,6,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
444720,2017/12/31 23,444790.0,142.0,387,709,481.61,5.28,4982.74,23,31,6,12,0
444721,2017/12/31 23,444791.0,143.0,84,160,101.59,0.00,987.19,23,31,6,12,0
444722,2017/12/31 23,444792.0,144.0,130,228,163.20,10.50,1628.20,23,31,6,12,0
444723,2017/12/31 23,444793.0,148.0,197,314,289.44,10.50,2657.04,23,31,6,12,0
444724,2017/12/31 23,444794.0,151.0,123,206,145.28,0.00,1570.68,23,31,6,12,0
444725,2017/12/31 23,444795.0,158.0,161,281,254.92,16.26,2289.38,23,31,6,12,0
444726,2017/12/31 23,444796.0,161.0,249,452,233.88,25.04,3535.12,23,31,6,12,0
444727,2017/12/31 23,444797.0,162.0,273,460,206.97,11.52,3313.34,23,31,6,12,0
444728,2017/12/31 23,444798.0,163.0,127,199,171.98,5.76,1904.84,23,31,6,12,0
444729,2017/12/31 23,444799.0,164.0,205,359,302.88,23.04,2971.92,23,31,6,12,0
444730,2017/12/31 23,444800.0,170.0,211,364,279.34,33.54,2693.18,23,31,6,12,0
444731,2017/12/31 23,444801.0,186.0,212,376,255.64,17.28,3052.52,23,31,6,12,0
444732,2017/12/31 23,444802.0,209.0,25,34,37.03,0.00,360.53,23,31,6,12,0
444733,2017/12/31 23,444803.0,211.0,86,147,95.74,0.00,1100.99,23,31,6,12,0
444734,2017/12/31 23,444804.0,224.0,23,49,31.98,0.00,278.88,23,31,6,12,0
444735,2017/12/31 23,444805.0,229.0,202,334,220.62,17.28,2598.75,23,31,6,12,0
444736,2017/12/31 23,444806.0,230.0,119,233,124.10,0.00,1683.30,23,31,6,12,0
444737,2017/12/31 23,444807.0,231.0,151,264,199.38,10.50,2173.53,23,31,6,12,0
444738,2017/12/31 23,444808.0,232.0,32,62,47.50,0.00,469.10,23,31,6,12,0
444739,2017/12/31 23,444809.0,233.0,92,163,98.15,11.52,1173.27,23,31,6,12,0
444740,2017/12/31 23,444810.0,234.0,273,460,364.28,11.52,3588.15,23,31,6,12,0
444741,2017/12/31 23,444811.0,236.0,286,472,316.23,11.52,3439.50,23,31,6,12,0
444742,2017/12/31 23,444812.0,237.0,247,419,221.83,8.30,2613.73,23,31,6,12,0
444743,2017/12/31 23,444813.0,238.0,299,551,330.78,5.76,3386.19,23,31,6,12,0
444744,2017/12/31 23,444814.0,239.0,290,521,354.04,0.00,3239.04,23,31,6,12,0
444745,2017/12/31 23,444815.0,246.0,90,134,102.99,5.76,1142.75,23,31,6,12,0
444746,2017/12/31 23,444816.0,249.0,238,416,356.29,27.56,3228.25,23,31,6,12,0
444747,2017/12/31 23,444817.0,261.0,48,68,62.18,5.76,883.34,23,31,6,12,0
444748,2017/12/31 23,444818.0,262.0,103,188,131.68,2.64,1213.47,23,31,6,12,0
444749,2017/12/31 23,444819.0,263.0,256,438,322.36,5.76,3025.92,23,31,6,12,0

In [61]:
dum['n_index'] = demand_data.index.tolist()

ValueError: Length of values does not match length of index

In [62]:
dum.set_index('n_index', inplace=True)

KeyError: 'n_index'

In [56]:
#X = demand_data['Hour'].values
#dum = pd.get_dummies(X)
demand_data = demand_data.join(dum, rsuffix = ' ')
#print(demand_data.shape)
#print(dum.shape)
#dum = dum.set_index(demand_data.index)  
#demand_data.merge(dum, left_index = True)
#demand_data = demand_data.add(dum)

In [58]:
demand_data.head

<bound method NDFrame.head of              time_block  Unnamed: 0  PULocationID  passenger_count  \
0         2017/01/01 00        70.0           4.0            135.0
0         2017/01/01 00        70.0           4.0            135.0
0         2017/01/01 00        70.0           4.0            135.0
0         2017/01/01 00        70.0           4.0            135.0
0         2017/01/01 00        70.0           4.0            135.0
0         2017/01/01 00        70.0           4.0            135.0
0         2017/01/01 00        70.0           4.0            135.0
0                   NaN         NaN           NaN              NaN
0                   NaN         NaN           NaN              NaN
0                   NaN         NaN           NaN              NaN
0                   NaN         NaN           NaN              NaN
0                   NaN         NaN           NaN              NaN
0                   NaN         NaN           NaN              NaN
0                   NaN         NaN           NaN              NaN
0                   NaN         NaN           NaN              NaN
0                   NaN         NaN           NaN              NaN
0                   NaN         NaN           NaN              NaN
0                   NaN         NaN           NaN              NaN
0                   NaN         NaN           NaN              NaN
0                   NaN         NaN           NaN              NaN
0                   NaN         NaN           NaN              NaN
0                   NaN         NaN           NaN              NaN
0                   NaN         NaN           NaN              NaN
0                   NaN         NaN           NaN              NaN
0                   NaN         NaN           NaN              NaN
0                   NaN         NaN           NaN              NaN
0                   NaN         NaN           NaN              NaN
0                   NaN         NaN           NaN              NaN
0                   NaN         NaN           NaN              NaN
0                   NaN         NaN           NaN              NaN
...                 ...         ...           ...              ...
14231970            NaN         NaN           NaN              NaN
14231971            NaN         NaN           NaN              NaN
14231972            NaN         NaN           NaN              NaN
14231973            NaN         NaN           NaN              NaN
14231974            NaN         NaN           NaN              NaN
14231975            NaN         NaN           NaN              NaN
14231976            NaN         NaN           NaN              NaN
14231977            NaN         NaN           NaN              NaN
14231978            NaN         NaN           NaN              NaN
14231979            NaN         NaN           NaN              NaN
14231980            NaN         NaN           NaN              NaN
14231981            NaN         NaN           NaN              NaN
14231982            NaN         NaN           NaN              NaN
14231983            NaN         NaN           NaN              NaN
14231984            NaN         NaN           NaN              NaN
14231985            NaN         NaN           NaN              NaN
14231986            NaN         NaN           NaN              NaN
14231987            NaN         NaN           NaN              NaN
14231988            NaN         NaN           NaN              NaN
14231989            NaN         NaN           NaN              NaN
14231990            NaN         NaN           NaN              NaN
14231991            NaN         NaN           NaN              NaN
14231992            NaN         NaN           NaN              NaN
14231993            NaN         NaN           NaN              NaN
14231994            NaN         NaN           NaN              NaN
14231995            NaN         NaN           NaN              NaN
14231996            NaN         NaN           NaN              NaN
14231997            NaN         NaN           NaN              NaN
14231998            NaN         NaN           NaN              NaN
14231999            NaN         NaN           NaN              NaN

          passenger_count.1  tip_amount  tolls_amount  total_amount  Hour  \
0                     260.0      188.94           0.0       2164.94   0.0
0                     260.0      188.94           0.0       2164.94   0.0
0                     260.0      188.94           0.0       2164.94   0.0
0                     260.0      188.94           0.0       2164.94   0.0
0                     260.0      188.94           0.0       2164.94   0.0
0                     260.0      188.94           0.0       2164.94   0.0
0                     260.0      188.94           0.0       2164.94   0.0
0                       NaN         NaN           NaN           NaN   NaN
0                       NaN         NaN           NaN           NaN   NaN
0                       NaN         NaN           NaN           NaN   NaN
0                       NaN         NaN           NaN           NaN   NaN
0                       NaN         NaN           NaN           NaN   NaN
0                       NaN         NaN           NaN           NaN   NaN
0                       NaN         NaN           NaN           NaN   NaN
0                       NaN         NaN           NaN           NaN   NaN
0                       NaN         NaN           NaN           NaN   NaN
0                       NaN         NaN           NaN           NaN   NaN
0                       NaN         NaN           NaN           NaN   NaN
0                       NaN         NaN           NaN           NaN   NaN
0                       NaN         NaN           NaN           NaN   NaN
0                       NaN         NaN           NaN           NaN   NaN
0                       NaN         NaN           NaN           NaN   NaN
0                       NaN         NaN           NaN           NaN   NaN
0                       NaN         NaN           NaN           NaN   NaN
0                       NaN         NaN           NaN           NaN   NaN
0                       NaN         NaN           NaN           NaN   NaN
0                       NaN         NaN           NaN           NaN   NaN
0                       NaN         NaN           NaN           NaN   NaN
0                       NaN         NaN           NaN           NaN   NaN
0                       NaN         NaN           NaN           NaN   NaN
...                     ...         ...           ...           ...   ...
14231970                NaN         NaN           NaN           NaN   NaN
14231971                NaN         NaN           NaN           NaN   NaN
14231972                NaN         NaN           NaN           NaN   NaN
14231973                NaN         NaN           NaN           NaN   NaN
14231974                NaN         NaN           NaN           NaN   NaN
14231975                NaN         NaN           NaN           NaN   NaN
14231976                NaN         NaN           NaN           NaN   NaN
14231977                NaN         NaN           NaN           NaN   NaN
14231978                NaN         NaN           NaN           NaN   NaN
14231979                NaN         NaN           NaN           NaN   NaN
14231980                NaN         NaN           NaN           NaN   NaN
14231981                NaN         NaN           NaN           NaN   NaN
14231982                NaN         NaN           NaN           NaN   NaN
14231983                NaN         NaN           NaN           NaN   NaN
14231984                NaN         NaN           NaN           NaN   NaN
14231985                NaN         NaN           NaN           NaN   NaN
14231986                NaN         NaN           NaN           NaN   NaN
14231987                NaN         NaN           NaN           NaN   NaN
14231988                NaN         NaN           NaN           NaN   NaN
14231989                NaN         NaN           NaN           NaN   NaN
14231990                NaN         NaN           NaN           NaN   NaN
14231991                NaN         NaN           NaN           NaN   NaN
14231992                NaN         NaN           NaN           NaN   NaN
14231993                NaN         NaN           NaN           NaN   NaN
14231994                NaN         NaN           NaN           NaN   NaN
14231995                NaN         NaN           NaN           NaN   NaN
14231996                NaN         NaN           NaN           NaN   NaN
14231997                NaN         NaN           NaN           NaN   NaN
14231998                NaN         NaN           NaN           NaN   NaN
14231999                NaN         NaN           NaN           NaN   NaN

          Day  ...    14.0   15.0   16.0   17.0   18.0   19.0   20.0   21.0   \
0         1.0  ...        0      0      0      0      0      0      0      0
0         1.0  ...        0      0      0      0      0      0      0      0
0         1.0  ...        0      0      0      0      0      0      0      0
0         1.0  ...        0      0      0      0      0      0      0      0
0         1.0  ...        0      0      0      0      0      0      0      0
0         1.0  ...        0      0      0      0      0      0      0      0
0         1.0  ...        0      0      0      0      0      0      0      0
0         NaN  ...        0      0      0      0      0      0      0      0
0         NaN  ...        0      0      0      0      0      0      0      0
0         NaN  ...        0      0      0      0      0      0      0      0
0         NaN  ...        0      0      0      0      0      0      0      0
0         NaN  ...        0      0      0      0      0      0      0      0
0         NaN  ...        0      0      0      0      0      0      0      0
0         NaN  ...        0      0      0      0      0      0      0      0
0         NaN  ...        0      0      0      0      0      0      0      0
0         NaN  ...        0      0      0      0      0      0      0      0
0         NaN  ...        0      0      0      0      0      0      0      0
0         NaN  ...        0      0      0      0      0      0      0      0
0         NaN  ...        0      0      0      0      0      0      0      0
0         NaN  ...        0      0      0      0      0      0      0      0
0         NaN  ...        0      0      0      0      0      0      0      0
0         NaN  ...        0      0      0      0      0      0      0      0
0         NaN  ...        0      0      0      0      0      0      0      0
0         NaN  ...        0      0      0      0      0      0      0      0
0         NaN  ...        0      0      0      0      0      0      0      0
0         NaN  ...        0      0      0      0      0      0      0      0
0         NaN  ...        0      0      0      0      0      0      0      0
0         NaN  ...        0      0      0      0      0      0      0      0
0         NaN  ...        0      0      0      0      0      0      0      0
0         NaN  ...        0      0      0      0      0      0      0      0
...       ...  ...      ...    ...    ...    ...    ...    ...    ...    ...
14231970  NaN  ...        0      0      0      0      0      0      0      0
14231971  NaN  ...        0      0      0      0      0      0      0      0
14231972  NaN  ...        0      0      0      0      0      0      0      0
14231973  NaN  ...        0      0      0      0      0      0      0      0
14231974  NaN  ...        0      0      0      0      0      0      0      0
14231975  NaN  ...        0      0      0      0      0      0      0      0
14231976  NaN  ...        0      0      0      0      0      0      0      0
14231977  NaN  ...        0      0      0      0      0      0      0      0
14231978  NaN  ...        0      0      0      0      0      0      0      0
14231979  NaN  ...        0      0      0      0      0      0      0      0
14231980  NaN  ...        0      0      0      0      0      0      0      0
14231981  NaN  ...        0      0      0      0      0      0      0      0
14231982  NaN  ...        0      0      0      0      0      0      0      0
14231983  NaN  ...        0      0      0      0      0      0      0      0
14231984  NaN  ...        0      0      0      0      0      0      0      0
14231985  NaN  ...        0      0      0      0      0      0      0      0
14231986  NaN  ...        0      0      0      0      0      0      0      0
14231987  NaN  ...        0      0      0      0      0      0      0      0
14231988  NaN  ...        0      0      0      0      0      0      0      0
14231989  NaN  ...        0      0      0      0      0      0      0      0
14231990  NaN  ...        0      0      0      0      0      0      0      0
14231991  NaN  ...        0      0      0      0      0      0      0      0
14231992  NaN  ...        0      0      0      0      0      0      0      0
14231993  NaN  ...        0      0      0      0      0      0      0      0
14231994  NaN  ...        0      0      0      0      0      0      0      0
14231995  NaN  ...        0      0      0      0      0      0      0      0
14231996  NaN  ...        0      0      0      0      0      0      0      0
14231997  NaN  ...        0      0      0      0      0      0      0      0
14231998  NaN  ...        0      0      0      0      0      0      0      0
14231999  NaN  ...        0      0      0      0      0      0      0      0

          22.0   23.0
0             0      0
0             0      0
0             0      0
0             0      0
0             0      0
0             0      0
0             0      0
0             0      0
0             0      0
0             0      0
0             0      0
0             0      0
0             0      0
0             0      0
0             0      0
0             0      0
0             0      0
0             0      0
0             0      0
0             0      0
0             0      0
0             0      0
0             0      0
0             0      0
0             0      0
0             0      0
0             0      0
0             0      0
0             0      0
0             0      0
...         ...    ...
14231970      0      0
14231971      0      0
14231972      0      0
14231973      0      0
14231974      0      0
14231975      0      0
14231976      0      0
14231977      0      0
14231978      0      0
14231979      0      0
14231980      0      0
14231981      0      0
14231982      0      0
14231983      0      0
14231984      0      0
14231985      0      0
14231986      0      0
14231987      0      0
14231988      0      0
14231989      0      0
14231990      0      0
14231991      0      0
14231992      0      0
14231993      0      0
14231994      0      0
14231995      0      0
14231996      0      0
14231997      0      0
14231998      0      0
14231999      0      0

[84502500 rows x 60 columns]>

In [ ]:
Y = demand_data['passenger_count']
X = demand_data[['PULocationID', 'Hour', 'Day_of_week', 'Month']]

In [18]:
reg = LinearRegression().fit(X, Y)
reg.predict(X)

444750